package com.example.exercisetracking

object Contants {

    const val ACTIVITY_DATABASE_NAME = "physAct_table"

    const val CODE_LOCATION_PERMISSION_REQUEST = 0

    const val START_RESUME_SERVICE_ACTION = "START_RESUME_SERVICE_ACTION"
    const val PAUSE_SERVICE_ACTION = "PAUSE_SERVICE_ACTION"
    const val STOP_SERVICE_ACTION = "STOP_SERVICE_ACTION"
    const val RUNNING_TRACKING_FRAGMENT = "RUNNING_TRACKING_FRAGMENT"
    const val WALKING_TRACKING_FRAGMENT = "WALKING_TRACKING_FRAGMENT"
}